---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cognyte-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: dev
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
      - name: http-server
        image: aleksva/k8s-exp:fb2e989a06c35b62e5306d98d83be68ed964abdb
        ports:
        - containerPort: 8080
        env:
        - name: candidate_name
          value: Aleksandar Andonov
---
apiVersion: v1
kind: Service
metadata:
  name: cognyte-svc
spec:
  selector:
    environment: dev
  ports:
  - port: 31080
    targetPort: 8080
...