---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cognyte-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: dev
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
      - name: http-server
        image: aleksva/k8s-exp:fb2e989a06c35b62e5306d98d83be68ed964abdb
        ports:
        - containerPort: 8080
        env:
        - name: candidate_name
          value: Aleksandar Andonov
---
apiVersion: v1
kind: Service
metadata:
  name: cognyte-svc
spec:
  selector:
    environment: dev
  ports:
  - port: 31080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio-controller
spec:
  controller: istio.io/ingress-controller
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: cognyte-istiocontrolplane
spec:
  profile: default # istiod + ingress 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cognyte-ingress
spec:
  ingressClassName: ingress-controller
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cognyte-svc
            port:
              number: 31080
...